# Generated by projekat 3.1.4 on 2020-12-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvozdje', '0002_auto_20201217_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mreza',
            old_name='odGvzdja',
            new_name='proizvedeno_Od',
        ),
    ]
